# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joyoungc
brief-intro: Back-end Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joyoungc.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username:
facebook_username:
github_username:  Joyoungc
email:
linkedIn_username:

description_footer:

# comments
# two ways to comment, only choose one, and use your own short name
disqus_shortname: joyoungc

# statistic analysis
google_analytics_id: UA-103165223-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  hard_wrap:      false
  footnote_nr:    1

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
